language: groovy

jdk:
    - openjdk7

before_install:
    - sudo add-apt-repository -y ppa:groovy-dev/grails
    - sudo apt-get update
    - sudo apt-get install grails-1.3.7

script: grails clean &&
    grails test-app unit:unit

notifications:
  email: false
  